<?php

// autoload.php @generated by Composer
// source_version = 60260

if ( file_exists( __DIR__ . '/composer/autoload_real.php' ) ) {
	require_once __DIR__ . '/composer/autoload_real.php';
	return ComposerAutoloaderInitcbff6516d78534c1c54b52afa641ae31::getLoader();
}



